version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app-dev
    ports:
      - "8080:80"
    volumes:
      # Mount source code for hot reload
      - ./:/app
      # Anonymous volume to prevent node_modules from being overwritten
      - /app/node_modules
    environment:
      - NODE_ENV=development
